name: 01 Env basic
on: workflow_dispatch

env:
  GLOBAL_FLAG: "on"
  SET_FLAG: "off"

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GLOBAL_FLAG=$GLOBAL_FLAG"
      - name: Steb-env überschreibt
        env:
          GLOBAL_FLAG: "off"
        run: echo "GLOBAL_FLAG=$GLOBAL_FLAG"
        
      - name: Set Flag  
        run: echo "SET_FLAG=$SET_FLAG"
      
      - name: Steb-env überschreibt
        env:
          SET_FLAG: "on"
        run: echo "SET_FLAG=$SET_FLAG"
        
        
        