name: 03 Secrets
on: workflow_dispatch

jobs:
    demo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "API_URL=${{ vars.API_URL }}"
            - name: Secret nutzen (maskiert)
              env:
                API_KEY: ${{ secrets.API_KEY }}
              run: echo "API_KEY lenght=${#API_KEY}"

