name: 05 Outputs
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.mk.outputs.image }}
    steps:
      - id: mk
        run: echo "image=repo/app:1.0.$(date +%H%M)" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Deploying ${{ needs.build.outputs.image }}"
